language: cpp
solution: burst-miner.sln
dist: precice

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

script: make
sudo: false
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
